#!/bin/bash

# check whether we were run on a local copy or curled and piped into a shell
[ -t 0 ] && piped=0 || piped=1

helpers_file=$(dirname $0)/_helpers.zsh
if (($piped)) || [ ! -f "$helpers_file" ]; then
  # this is duplicated from _helpers.zsh so that this can be piped into a shell
  function color  { echo -e "\033[$1m$2\033[0m"; }
  function green  { color "0;32" "$1"; }
  function yellow { color "1;33" "$1"; }
else
  source $helpers_file
fi

# check/install homebrew, we need this for installing software
if [ -x "$(command -v brew)" ]; then
  green "homebrew is already installed"
else
  yellow "homebrew is missing, installing..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if (($piped)); then
  read -p "where to install homebrew to [~/.config/dotfiles]: " dotfiles_dir
  dotfiles_dir=${dotfiles_dir:-~/.config/dotfiles}

  brew install git
  git clone git@github.com:thomasjachmann/dotfiles.git $dotfiles_dir
else
  dotfiles_dir=$(dirname $0)
fi

# bin/dotfiles needs grealpath to determine the dotfiles home dir
if [ -x "$(command -v grealpath)" ]; then
  green "coreutils (grealpath) is already installed"
else
  yelow "coreutils (grealpath) is missing, installing..."
  brew install coreutils
fi

yellow "installing zsh and homebrew dotfile packages"
$dotfiles_dir/zsh/bin/dotfiles install homebrew zsh

green "done"
