#!/bin/bash

set -e

# check whether we were run on a local copy or curled and piped into a shell
[ -t 0 ] && piped=0 || piped=1

helpers_file=$(dirname $0)/_helpers.zsh
if (($piped)) || [ ! -f "$helpers_file" ]; then
  # this is duplicated from _helpers.zsh so that this can be piped into a shell
  function color  { echo -e "\033[$1m$2\033[0m"; }
  function green  { color "0;32" "$1"; }
  function yellow { color "1;33" "$1"; }
else
  source $helpers_file
fi

function available() {
  if [ -x "$(command -v $1)" ]; then
    green "$1 is available"
    return 0
  else
    yellow "$1 is missing, installing..."
    return 1
  fi
}

# we need homebrew for installing software
available brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# bin/dotfiles needs grealpath to determine the dotfiles home dir
available grealpath || brew install coreutils
# bin/dotfiles needs chezmoi to symlink config files
available chezmoi || brew install chezmoi

if (($piped)); then
  default=${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles/vault
  read -p "where to install homebrew to [$default]: " dotfiles_dir
  dotfiles_dir=${dotfiles_dir:-$default}
  git clone https://github.com/thomasjachmann/dotfiles.git $dotfiles_dir
else
  dotfiles_dir=$(dirname $0)
fi

yellow "installing zsh and homebrew dotfile packages"
$dotfiles_dir/zsh/bin/dotfiles install homebrew zsh oh-my-zsh

green "done"
