#!/bin/bash

source $(dirname $0)/_helpers.zsh

# check/install homebrew, we need this for installing software
if [ -x "$(command -v brew)" ]; then
  green "homebrew is already installed"
else
  yellow "homebrew is missing, installing..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# bin/dotfiles needs grealpath to determine the dotfiles home dir
if [ -x "$(command -v grealpath)" ]; then
  green "coreutils (grealpath) is already installed"
else
  yelow "coreutils (grealpath) is missing, installing..."
  brew install coreutils
fi

yellow "installing zsh and homebrew dotfile packages"
$dotfiles_dir/zsh/bin/dotfiles install homebrew zsh

green "done"
