alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."
alias .........="cd ../../../../../../../.."
alias ls="ls -G"
alias ll="ls -l"
alias la="ls -la"
alias lh="ls -lah"
alias l="lh"
alias t="term -t"

alias reload="say-and-execute source ~/.profile"
alias edit="say-and-execute mate ~/.profile.d"
