#!/bin/bash

set -e

[ -x "$(command -v pip)" ] && pip install neovim
[ -x "$(command -v pip3)" ] && pip3 install neovim

nvim -c PlugInstall -c qall

cp -prf $(dirname $0)/support/OpenInNvim.app /Applications
cp -prf $(dirname $0)/support/VimWiki.app /Applications
