[settings]
experimental = true

[tools]
ruby = "latest"
node = "latest"
bun = "latest"
yarn = "1.22.19" # see https://github.com/twuni/asdf-yarn/issues/33
pnpm = "latest"
go = "latest"
rust = "latest"
python = "latest"

[env]
RTX_HIDE_UPDATE_WARNING = "1" # I'll update using homebrew anyway
