brew "zsh"
brew "stow"
brew "coreutils"
brew "zsh-syntax-highlighting"

# TODO: zplug or any zsh plugin manager? zplug is meant to work in the spirit of vim-plug.
# TODO: https://invidio.us/watch?v=eLEo4OQ-cuQ tipps on vi mode, cursor change etc
