#!/bin/bash

source $(dirname $0)/../_colors.zsh

# check availability of zsh as login shell
if grep --quiet -e "^/usr/local/bin/zsh$" /etc/shells; then
  green "zsh is already available as login shell"
else
  yellow "zsh is not available as login shell, adding it to /etc/shells"
  echo -e "\n# make current zsh installed via homebrew available as login shell\n/usr/local/bin/zsh" \
    | sudo tee -a /etc/shells > /dev/null
fi

# check user's shell
if [ "$SHELL" == "/usr/local/bin/zsh" ]; then
  green "your user already uses zsh"
else
  yellow "you should set your user's shell to use zsh: chsh -s /usr/local/bin/zsh"
fi
