#!/bin/bash

set -e

source $(dirname $0)/../_helpers.zsh

yellow "you need to adjust your settings and import color preset $(grealpath $(dirname $0))/support/tja.itermcolors"

# TODO make configuration reproducible
#
# Just adding ~/Library/Preferences/com.googlecode.iterm2.plist here doesn't do
# the trick. There are values in there that are more volatile than mere
# settings (eg the last working directory), so it would change all the time.
# Plus, iTerm recreates the file on each change, deleting the symlink and
# creating a new file, so changes made in the app wouldn't show up in here.
